Document: aws-sg
Title: Debian aws-sg Manual
Author: <insert document author here>
Abstract: This manual describes what aws-sg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aws-sg/aws-sg.sgml.gz

Format: postscript
Files: /usr/share/doc/aws-sg/aws-sg.ps.gz

Format: text
Files: /usr/share/doc/aws-sg/aws-sg.text.gz

Format: HTML
Index: /usr/share/doc/aws-sg/html/index.html
Files: /usr/share/doc/aws-sg/html/*.html
